# Generated by Django 4.0.3 on 2022-04-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tituloAviso', models.CharField(max_length=40)),
                ('contenidoAviso', models.CharField(max_length=40)),
            ],
        ),
    ]
